version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.17.6
        auth:
          username: ${DOCKER_USERNAME}
          password: ${DOCKER_PASSWORD}
    steps:
      - checkout # check out the code in the project directory
      - run:
          command: |
            export NODE_ENV=development && \
              npm ci --save-dev --production=false && \
              webpack --config webpack.config.js
