aws:
  accessKeyId:
  appSecretName:
  region:
  secretAccessKey:
  secretName:

env: dev
image:
  repository: jalgraves/beantown
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

containerPort: 3000

ingress:
  enabled: false

logLevel: tiny

nodeEnv: ""
regionCode:
resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    memory: 350Mi
